name: Calculator PyTest
permissions: write-all

on:
  workflow_dispatch:

jobs:
  test:
    name: Run PyTest
    runs-on: ubuntu-latest  # Use the appropriate runner for your needs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
      - name : Pytest install lib
        run  : pip install pytest
      - name: Run PyTest
        run: pytest -rp calculator_pytest.py > test${{github.run_number}}.txt

#       - name: Store Result
#         run: |
#           random_filename=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
#           mv test_result.txt $random_filename.txt

      - name: Commit and push
        run: |
            git config --local user.email "nhakobyan685@gmail"
            git config --local user.name "nhakobyan685"
            git add test${{github.run_number}}.txt
            git commit -m "Tests ${{github.run_number}}"
      - name : Push
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}
